### ISSUE TITLE
WILLY LA CHOOOVE

### ISSUE THREAD

**Issue by xodamcm** [HiroshimaTeam/AreaGuard#6]
Willy et son ekipe d handicapew

**Comment by SayaAEP** [comment]
you like a 8yo. stop

**Comment by xodamcm** [comment]
Et cbon j’suis un gamin d’avoir fais ca mais ce genre de mec qui se prétende développeur, createur de plugin sur mesure mais qui repond pas aux commandes, faut les envoyer tapinner au madams

**Comment by SayaAEP** [comment]
yea but just wait the dev make fixed version

> Et cbon j’suis un gamin d’avoir fais ca mais ce genre de mec qui se prétende développeur, createur de plugin sur mesure mais qui repond pas aux commandes, faut les envoyer tapinner au madams
